### ISSUE TITLE
2024-05-28 API updates and missing channels

### ISSUE THREAD

**Issue by 0xabu** [chkuendig/tv7-epg-parser#2]
Thanks for doing the work to reverse engineer and automate EPG fetching! I've been using your script for some time now but ran into a few hiccups after the TV7 updates on May 28, which also included many changes to the set of channels, channel names, and renumbering.

The first thing you may be interested to know is that the API appears to have a new (stable?) home at `https://api.tv.init7.net/api/`

The second thing I noticed is that some channels are missing in the API -- https://api.tv.init7.net/api/tvchannel/ includes data for 105 channels, but https://api.init7.net/tvchannels.m3u lists 212 (as of last night, anyway).

The missing channel IDs are:
> 24Horas.es 5Plus.ch 5STAR.uk 5USA.uk 6Plus.ch ARDalpha.de AlJazeera.qa AnixeHDSerie.de AuftankenTV.ch BBCFour.uk BBCNewsEurope.uk BNTV.ba BVN.nl BibelTV.de CBBC.uk CBeebies.uk CNNTurk.tr CanalPlus.fr Cartoonito.it Channel5.uk Cine34.it ComedyCentral.de DMAX.de DMAX.it DWEnglish.de DeejayTV.it DeluxeMusic.de DreamTurk.tr Duna.hu EuroD.tr EuroStar.tr FashionTVEurope.fr Film4.uk Focus.it France24English.fr France24French.fr France5.fr Frisbee.it Giallo.it Haberturk.tr ITV3.uk ITV4.uk K2.it Kanal7.tr LFMTV.ch LiloTV.de MDRFernsehenSachsen.de MTV.de More4.uk N24Doku.de NDRFernsehenHamburg.de Nitro.de Nove.it One.de OneTV.ch ProSiebenMaxx.de RMCStory.fr RTK1.xk RTL1025TV.it RTPInternacional.pt RTSH3.al RTSSvet.rs RadioItaliaTV.it Rai5.it RaiScuola.it RaiStoria.it RealTime.it RougeTV.ch SAT1Gold.de SRFernsehen.de ServusTV.at SkyNewsInternational.uk Sportitalia.it StarTV.ch SuperTennis.it TELE5.de TGRTEU.tr TLC.de TRT1.tr TRTCocuk.tr TRTHaber.tr TRTSpor.tr TRTTurk.tr TV2000.it TVCG.me TVEInternacionalEuropeAsia.es TVM3.ch TVPPolonia.pl TVRInternational.ro TVSuissePlus.ch TeleD.ch TeleSwizz.ch TeleVersoix.ch TeleZ.ch Telelombardia.it TravelXP.uk WELT.de WettercomTV.de ZDFinfo.de ZDFneo.de hrfernsehen.de kabeleinsDoku.de phoenix.de rbbFernsehenBerlin.de sixx.de tagesschau24.de tv4e.gr

(I guess the next step is seeing whether these channels are available with EPG in the app and/or doing some more reverse engineering -- just to be clear I don't expect you to do that but wanted to report my findings.)

**Comment by chkuendig** [comment]
Thanks for this report, it seems that the TV7 App only has 100+ channels now. See [Bits & Bites #06](https://init7.friendlyautomate.ch/email/preview/167#title-id-11):

> Init7 is revising the programme portfolio in the TV7 app and reorganising the TV infrastructure. This will improve the clarity and reliability of TV7. The TV app will continue to include over 100 channels in DE, FR, IT and EN.
> ...
> The multicast portfolio will continue to be available with more than 200 TV channels as a playlist. The switchover will take place automatically on 28 May 2024.

**Comment by 0xabu** [comment]
Oh, darn. Then it sounds like this is probably expected. I might need to look for another source of EPG data for some of those channels.

**Comment by damnms** [comment]
There is also some sort of problem with the mapping. I noticed that "Comedy Central" (as example) is in the .xml, but its somehow not shown in IPTVSimple's EPG.

**Comment by damnms** [comment]
It seems like (for me as noob) that the .xml is not well-formed. there is a tool called tv_validate_file which does xmltv validation (see https://man.freebsd.org/cgi/man.cgi?query=tv_validate_file&manpath=FreeBSD+Ports+10.2-RELEASE, its in the debian package xmltv-gui) which validates against the "official" .dtd. 

after validation, there are lot of these:
The file is not valid according to the xmltv dtd:
 IdeaProjects/myproject/init7-xmltv-cleaned.xml:919: validity error : Element programme content does not follow the DTD, expecting (title+ , sub-title* , desc* , credits? , date? , category* , keyword* , language? , orig-language? , length? , icon* , url* , country* , episode-num* , video? , audio? , previously-shown? , premiere? , last-chance? , new? , subtitles* , rating* , star-rating* , review* , image*), got (language title sub-title desc category category country date icon )

i called it only cleaned because i used tidy to compare it with other .xml epg information to find the error.

**Comment by spali** [comment]
@0xabu Are you sure `https://api.tv.init7.net/api/` is the new goto endpoint?

I always assumed `https://api.tv.init7.net/api/` was an old one and new one was `https://tv7api2.tv.init7.net/api/` which is now not available (at least for me).
My assumption was based on `https://tv7api2.tv.init7.net/api/` returned more channels which matched better to the m3u file (even some mappings didn't work out of the box).
`https://api.tv.init7.net/api/` retuns 105 channels.  `https://tv7api2.tv.init7.net/api/` did return 183 (at least till 3. June as I last dowloaded the channel list from the api).
But I never was entirely sure about the different endpoints and also why some of the multicast addresses didn't match from one api to the other and not to the m3u file. 😕 

In case you are right... we would potentially loose EPG for all channels probably not included in the App and also another source (beside m3u) for the multicast addresses. 😢

**Comment by 0xabu** [comment]
I'm not sure of anything at all :) I just noticed that this host is where the tvchannels.m3u file is served from, and it has an API endpoint that is compatible with the script in this repo. Moreover, tv7api2 doesn't seem to be responsive any more, and I don't think it's too surprising that the EPG data from Init7 is limited to the channels in the app -- why would they carry more, in their own private API?

**Comment by spali** [comment]
Just found (used on the website, not sure if new): `https://api.init7.net/fiber7-tv-channels.v2.json?lang_order=en&streaming_type=all`
which returns 212 channels. Didn't compare channel by channel, but the number would match exactly with the m3u file.
So it seems to me that the endpoint has all channels, but doesn't provide it in the channel list for the app.
And it seems also that epg does return data for the channels. Tested with `https://api.tv.init7.net/api/epg/?channel=097e7335-98c5-48ad-b9b8-315799df5cf8&limit=1` the channel `5+` is not in the app.
For me this solved a lot of mismatch between the v2 and this endpoint and also between the m3u file.
And also seems to point to the fact and confirm your assumption, that `https://api.init7.net` is the "new" endpoint.

So with this, it looks like that we can get epg for (hopefully) all these channels.
When I have time, I try to work on a script to build the m3u (including the FHD channels) and match them to epg data to check if there is anything missing.

BTW: they also have now m3u for HLS... check the page: https://www.init7.net/en/tv/channels/ at the top right.

**Comment by spali** [comment]
Not related to this issue, but may help too... didn't see this before. With nerdmode enabled, they have now more technical info about the ip ranges for the multicast traffik:
https://www.init7.net/en/support/faq/mit-welchen-uebertragungsarten-funktionieren-die-tv-streams/

Which allows to reduce the firewall rules for the multicast traffic to a single `77.109.129.0/24` subnet for the source and two multicast subnets (`239.77.0.0/16` and `233.50.230.0/24`) port 5000 as targets. I think most and me used to use `77.109.128.0/19` which is a lot more open.

**Comment by damnms** [comment]
thanks, i thought they blocked my ip or so because the "old" api was not available anymore for me too ;)

**Comment by spali** [comment]
thanks to the new web page channel overview, I found out the parameter `https://api.tv.init7.net/api/tvchannel/?streaming_type=all` also returns 212 channels. So it's possible to get all information from the api without the m3u. Which would finally solve matching problems between m3u names with epg names (had always mismatches between `tvg-name` from the m3u and EPG's `canonical_name`).
So the only matching required now is for the 7 FHD channels from the FHD m3u.

**Comment by 0xabu** [comment]
Oh, fantastic. Thanks for the sleuthing, @spali!

**Comment by chkuendig** [comment]
That's a great find and makes fixing this issue super straightforward. I should be able to put together a fix pretty quickly.

**Comment by 0xabu** [comment]
This is a bit off-topic, but given the knowledgeable audience I'll ask anyway: I don't seem to receive any multicast stream for on BBC Four (udp://233.50.230.165:5000). All the other multicast streams work, but this one doesn't deliver anything. Is anyone else seeing the same?

**Comment by chkuendig** [comment]
Same here, BBC Four doesn't work
